# Generated by Django 5.2.17 on 2026-10-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_sec', models.FloatField(default=0.0)),
                ('kind', models.CharField(max_length=100)),
                ('source_role', models.CharField(default='HQ', max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truth_events', to='exercises.exercise')),
                ('scenario_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.scenarioevent')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('DROPPED', 'Dropped')], default='PENDING', max_length=20)),
                ('origin', models.CharField(choices=[('NORMAL', 'Normal'), ('CONFLICT', 'Conflict'), ('SPOOFED', 'Spoofed')], default='NORMAL', max_length=20)),
                ('confidence', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROBABLE', 'Probable'), ('UNVERIFIED', 'Unverified')], default='UNVERIFIED', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('is_corrupted', models.BooleanField(default=False)),
                ('delay_sec', models.FloatField(default=0.0)),
                ('deliver_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='exercises.exercise')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='exercises.participant')),
                ('truth_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='comms.truthevent')),
            ],
            options={
                'ordering': ['deliver_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MOVE', 'Move'), ('HOLD', 'Hold'), ('FIRE_SUPPORT', 'Fire Support'), ('REQUEST_ISR', 'Request ISR'), ('VERIFY', 'Verify Comms/Data'), ('FALLBACK_COMMS', 'Switch to Fallback Comms')], max_length=30)),
                ('self_confidence', models.FloatField(help_text='0.0 to 1.0 (from confidence slider)')),
                ('latency_sec', models.FloatField(default=0.0)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='exercises.exercise')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='exercises.participant')),
                ('truth_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='comms.truthevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
