# Generated by Django 5.2.17 on 2026-10-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('domains', models.JSONField(default=list, help_text="e.g. ['LAND', 'AIR', 'CYBER', 'EW']")),
                ('roles', models.JSONField(default=list, help_text="e.g. ['LAND', 'AIR', 'CYBER']")),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXTREME', 'Extreme')], default='MEDIUM', max_length=20)),
                ('center_lat', models.FloatField(default=25.4358)),
                ('center_lon', models.FloatField(default=81.8463)),
                ('default_intensity', models.FloatField(default=0.3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_offset_sec', models.PositiveIntegerField(help_text='Seconds from exercise start')),
                ('event_type', models.CharField(choices=[('TRUTH', 'Truth Event'), ('LINK_DOWN', 'Link Down'), ('LINK_UP', 'Link Up'), ('JAM_ZONE', 'Jam Zone')], default='TRUTH', max_length=30)),
                ('kind', models.CharField(default='TACTICAL_REPORT', max_length=100)),
                ('source_role', models.CharField(default='HQ', max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='{title, detail, lat, lon, visible_to, expected_actions}')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['t_offset_sec', 'id'],
            },
        ),
    ]
