# Generated by Django 5.2.17 on 2026-10-03 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='LOBBY', max_length=20)),
                ('intensity', models.FloatField(default=0.3)),
                ('seed', models.PositiveIntegerField(default=123456)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_before', models.FloatField(default=0.0)),
                ('fired_event_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_exercises', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='JammingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius_m', models.FloatField(default=5000.0)),
                ('intensity', models.FloatField(default=0.8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamming_zones', to='exercises.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='CommLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_role', models.CharField(max_length=50)),
                ('target_role', models.CharField(max_length=50)),
                ('quality', models.FloatField(default=1.0)),
                ('is_up', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='exercises.exercise')),
            ],
            options={
                'unique_together': {('exercise', 'source_role', 'target_role')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exercise', 'user')},
            },
        ),
    ]
